name: Test
on: [push]
jobs:
  C tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          cd c
          mkdir bin
          make test
